# Generated by roxytest: Do not edit by hand!


test_that("Function write_gedcom() @ L16", {
  expect_warning(write_gedcom(read_gedcom(system.file("extdata", "555SAMPLE.GED", package = "tidyged.io")), 
                              "my_family.txt"))
})


test_that("Function update_header_with_filename() @ L55", {
  expect_snapshot_value(read_gedcom(system.file("extdata", "555SAMPLE.GED", package = "tidyged.io")) %>% 
                          update_header_with_filename("my_file.ged"), "json2")
  expect_snapshot_value(read_gedcom(system.file("extdata", "MINIMAL555.GED", package = "tidyged.io")) %>% 
                          update_header_with_filename("my_file2.ged"), "json2")
})

