# Generated by roxytest: Do not edit by hand!

# File R/export.R: @tests

test_that("Function write_gedcom() @ L17", {
  expect_warning(write_gedcom(read_gedcom(system.file("extdata", "555SAMPLE.GED", package = "tidyged.io")), 
                              "my_family.txt"))
   file.remove("my_family.txt")
})


test_that("Function update_header_with_filename() @ L57", {
  expect_snapshot_value(read_gedcom(system.file("extdata", "555SAMPLE.GED", package = "tidyged.io")) %>% 
                          update_header_with_filename("my_file.ged"), "json2")
  expect_snapshot_value(read_gedcom(system.file("extdata", "MINIMAL555.GED", package = "tidyged.io")) %>% 
                          update_header_with_filename("my_file2.ged"), "json2")
})

